# Generated by Django 5.0.6 on 2024-07-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='google_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
