# Generated by Django 5.0.6 on 2024-08-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0002_position_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_num', models.CharField(max_length=10)),
                ('player_name', models.CharField(max_length=100)),
                ('player_country', models.CharField(max_length=50)),
                ('player_role', models.CharField(max_length=50)),
                ('player_image', models.ImageField(upload_to='player_images/')),
                ('player_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserHandle.position')),
            ],
        ),
    ]
