# Generated by Django 5.0.6 on 2024-07-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0002_users_google_email_users_google_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='google_email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='google_token',
        ),
    ]
