# Generated by Django 5.0.6 on 2024-08-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('news_image', models.ImageField(upload_to='news_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
