# Generated by Django 5.0.6 on 2024-08-05 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0006_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demography_name', models.CharField(max_length=50)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserHandle.subcategory')),
            ],
        ),
    ]
