# Generated by Django 5.0.6 on 2024-08-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0007_demography'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demography',
        ),
    ]
