# Generated by Django 5.0.6 on 2024-08-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0014_alter_cart_user_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
