# Generated by Django 5.0.6 on 2024-08-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0016_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
