# Generated by Django 5.0.6 on 2024-08-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0018_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
