# Generated by Django 5.0.6 on 2024-08-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0021_alter_cartitem_unique_together_cart_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
