# Generated by Django 5.0.6 on 2024-09-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0031_alter_section_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='seats',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
