# Generated by Django 5.0.6 on 2024-09-01 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0032_section_seats_delete_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
