# Generated by Django 5.0.6 on 2024-09-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0035_ticketorder_seatavailability_ticketitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatavailability',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='seatavailability',
            name='last_assigned_seat',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='seatavailability',
            name='available_seats',
        ),
    ]
