# Generated by Django 5.0.6 on 2024-09-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0036_alter_seatavailability_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketitem',
            name='seat_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SeatAvailability',
        ),
    ]
