# Generated by Django 5.0.6 on 2025-02-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0039_alter_order_address_order_apartment_order_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('options', models.JSONField()),
                ('correct_answers', models.JSONField()),
            ],
        ),
    ]
