# Generated by Django 5.0.6 on 2025-02-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0040_quizquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.TextField(),
        ),
    ]
