# Generated by Django 5.0.6 on 2025-02-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0043_uploadedimage_delete_jigsawimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='players/')),
            ],
        ),
    ]
