# Generated by Django 5.0.6 on 2025-02-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0044_identifyplayer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifyplayer',
            name='image',
            field=models.ImageField(upload_to='guess_players/'),
        ),
    ]
