# Generated by Django 5.0.6 on 2025-02-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0048_playercredentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketorder',
            options={'ordering': ['-created_at']},
        ),
    ]
