# Generated by Django 5.0.6 on 2025-02-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0049_alter_ticketorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketorder',
            options={},
        ),
        migrations.CreateModel(
            name='PlayerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('video_required', models.BooleanField(default=True)),
                ('video_submission', models.FileField(blank=True, null=True, upload_to='task_submissions/')),
                ('assigned_players', models.ManyToManyField(related_name='assigned_tasks', to='UserHandle.player')),
            ],
        ),
    ]
