# Generated by Django 5.0.6 on 2025-02-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0050_alter_ticketorder_options_playertask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertask',
            name='video_submission',
        ),
    ]
