# Generated by Django 5.0.6 on 2025-03-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0053_player_appearances_player_assists_player_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketitem',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
