# Generated by Django 5.0.6 on 2025-03-17 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0054_ticketitem_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='player_videos/')),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/')),
                ('pose_data', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='UserHandle.player')),
            ],
        ),
    ]
