# Generated by Django 5.0.6 on 2025-03-18 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0055_playervideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertask',
            name='assigned_players',
        ),
        migrations.RemoveField(
            model_name='playertask',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='playertask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playertask',
            name='title',
        ),
        migrations.RemoveField(
            model_name='playertask',
            name='video_required',
        ),
        migrations.RemoveField(
            model_name='playervideo',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playervideo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='playervideo',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='playertask',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='playertask',
            name='exercise_type',
            field=models.CharField(choices=[('pushup', 'Push-Ups'), ('squat', 'Squats'), ('jump', 'Jumps'), ('sprint', 'Sprints'), ('burpee', 'Burpees'), ('lunge', 'Lunges'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='playertask',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertask',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='UserHandle.player'),
        ),
        migrations.AddField(
            model_name='playertask',
            name='repetitions',
            field=models.IntegerField(blank=True, help_text='Number of repetitions to perform', null=True),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='UserHandle.playertask'),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='trainer_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertask',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('evaluated', 'Evaluated')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='player_videos/'),
        ),
    ]
