# Generated by Django 5.0.6 on 2025-03-18 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0056_remove_playertask_assigned_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertask',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserHandle.player'),
        ),
    ]
