# Generated by Django 5.0.6 on 2025-03-18 04:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0057_alter_playertask_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertask',
            options={'ordering': ['-assigned_date']},
        ),
        migrations.AlterField(
            model_name='playertask',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playertask',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playertask',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='UserHandle.player'),
        ),
        migrations.AlterField(
            model_name='playertask',
            name='repetitions',
            field=models.IntegerField(default=0, help_text='Number of repetitions to perform'),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='UserHandle.playertask'),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
