# Generated by Django 5.0.6 on 2025-03-18 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0059_playervideo_evaluation_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playervideo',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='playervideo',
            old_name='evaluation_result',
            new_name='evaluation_data',
        ),
        migrations.RemoveField(
            model_name='playervideo',
            name='pose_data',
        ),
        migrations.RemoveField(
            model_name='playervideo',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='playervideo',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='UserHandle.player'),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='UserHandle.playertask'),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='video',
            field=models.FileField(upload_to='player_videos/'),
        ),
    ]
