# Generated by Django 5.0.6 on 2025-03-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0060_alter_playervideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playervideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
