# Generated by Django 5.0.6 on 2025-03-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0062_alter_playervideo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='playervideo',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playervideo',
            name='processing_progress',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='evaluation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
