# Generated by Django 5.0.6 on 2025-03-19 08:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserHandle', '0063_playervideo_error_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playervideo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='UserHandle.player'),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playervideo',
            name='video',
            field=models.FileField(upload_to='player_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'wmv'])]),
        ),
    ]
